-- KERS Sensor
-- create new part type: KERS Sensor
INSERT INTO vehicle_part_types (part_type) VALUES ('KERS Sensor');

-- create new entries in firmware components table
INSERT INTO firmware_components (part_type, firmware_component) VALUES ('KERS Sensor', 'Inverter Profile - Left');

-- create entry in vehicle_model_parts for old and new KERS sensor
-- firmware_release_id is being set to the same as the Inverters item in this table
-- FUV
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Original Manufactured'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'KERS Sensor', '001412', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
-- Camera Car
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'KERS Sensor', '001412', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
-- Deliverator
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'KERS Sensor', '001412', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
-- Rapid Responder
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'KERS Sensor', '001412', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
-- Responderator
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'KERS Sensor', '001412', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
-- Roadster
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'KERS Sensor', '001325', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'KERS Sensor', '001412', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));

-- all existing vehicles need to have the old KERS sensor marked as installed in vehicle_parts_installed table
-- if manufactured after (inclusive) KERS Sensor cutover VIN (7F7ADR311MER00019) then update part_number
-- skips vehicles that don't have any other parts (provisioned but not completed initial check-in to the cloud)
INSERT INTO vehicle_parts_installed (vin, part_type, part_number) SELECT v.vin, 'KERS Sensor', '001325' from vehicle v WHERE v.vin IN (select DISTINCT vin from vehicle_parts_installed);
-- NOTE: VIN prefix must be updated on this line per ENV
UPDATE vehicle_parts_installed SET part_number = '001412' WHERE part_type = 'KERS Sensor' AND vin IN (select vin from vehicle where created >= (select created from vehicle where vin = 'DEV-7F7ADR311MER00019')) AND vin IN (select DISTINCT vin from vehicle_parts_installed);

-- all existing vehicles need to have the old KERS sensor marked as installed in vehicle_firmware_installed table
-- if manufactured after (inclusive) KERS Sensor cutover VIN (7F7ADR311MER00019) then update firmware for `Inverter - Left`
-- skips vehicles that don't have any other parts (provisioned to exist but not completed initial check-in to the cloud)
-- match new entry to firmware_release_id of `Inverters:Inverter Profile - Left` for vin
INSERT INTO vehicle_firmware_installed (vin, part_type, firmware_component, firmware_release_id) SELECT v.vin, 'KERS Sensor', 'Inverter Profile - Left', (select firmware_release_id from vehicle_firmware_installed where part_type = 'Inverters' and firmware_component = 'Inverter Profile - Left' and v.vin IN (select DISTINCT vin from vehicle_parts_installed) order by firmware_release_id DESC limit 1) from vehicle v WHERE v.vin IN (select DISTINCT vin from vehicle_parts_installed);
-- NOTE: VIN prefix must be updated on this line per ENV
UPDATE vehicle_firmware_installed SET firmware_release_id = (select firmware_release_id from firmware_release where part_type = 'Inverter - Left' and firmware_component = 'Inverter Profile - Left') WHERE firmware_component = 'Inverter Profile - Left' AND vin IN (select vin from vehicle where created >= (select created from vehicle where vin = 'DEV-7F7ADR311MER00019')) AND vin IN (select DISTINCT vin from vehicle_parts_installed);
