-- insert platform to allow models to be inserted
INSERT INTO vehicle_platform (platform_name, description) VALUES ('FUV 1.0', 'Original manufactured platform');
-- vehicle_model table: create models
INSERT INTO vehicle_model (model_name, letter_code, platform_id, description) VALUES ('FUV', 'T', (select id from vehicle_platform where platform_name='FUV 1.0'), 'FUV standard, dual seats');
INSERT INTO vehicle_model (model_name, letter_code, platform_id, description) VALUES ('Camera Car', 'C', (select id from vehicle_platform where platform_name='FUV 1.0'), 'Rear mounted camera, single seat');
INSERT INTO vehicle_model (model_name, letter_code, platform_id, description) VALUES ('Deliverator', 'D', (select id from vehicle_platform where platform_name='FUV 1.0'), 'Rear delivery compartment, single seat');
INSERT INTO vehicle_model (model_name, letter_code, platform_id, description) VALUES ('Rapid Responder', 'E', (select id from vehicle_platform where platform_name='FUV 1.0'), 'Vehicle ready to be outfitted with emergency equipment, dual seats');
INSERT INTO vehicle_model (model_name, letter_code, platform_id, description) VALUES ('Responderator', 'F', (select id from vehicle_platform where platform_name='FUV 1.0'), 'Vehicle ready to be outfitted with emergency equipment, rear compartment, single seat');
INSERT INTO vehicle_model (model_name, letter_code, platform_id, description) VALUES ('Roadster', 'R', (select id from vehicle_platform where platform_name='FUV 1.0'), 'Motorcycle like low profile vehicle, dual seats');

-- vehicle_model_release table - create model_releases for all existing models
-- FUV
UPDATE vehicle_model_release SET model_id = (select id from vehicle_model where model_name='FUV') WHERE description = 'Standard FUV';
UPDATE vehicle_model_release SET description = 'FUV: Original Manufactured' WHERE model_id = (select id from vehicle_model where model_name='FUV');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='FUV'), 'FUV: Discoboard');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='FUV'), 'FUV: KERS Sensor');
-- Camera Car
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Camera Car'), 'Camera Car: Original Manufactured');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Camera Car'), 'Camera Car: Discoboard');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Camera Car'), 'Camera Car: KERS Sensor');
-- Deliverator
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Deliverator'), 'Deliverator: Original Manufactured');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Deliverator'), 'Deliverator: Discoboard');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Deliverator'), 'Deliverator: KERS Sensor');
-- Rapid Responder
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Rapid Responder'), 'Rapid Responder: Original Manufactured');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Rapid Responder'), 'Rapid Responder: Discoboard');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Rapid Responder'), 'Rapid Responder: KERS Sensor');
-- Responderator
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Responderator'), 'Responderator: Original Manufactured');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Responderator'), 'Responderator: Discoboard');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Responderator'), 'Responderator: KERS Sensor');
-- Roadster
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Roadster'), 'Roadster: Original Manufactured');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Roadster'), 'Roadster: Discoboard');
INSERT INTO vehicle_model_release (model_id, description) VALUES ((select id from vehicle_model where model_name='Roadster'), 'Roadster: KERS Sensor');

-- Inverter changes
-- change unique constraint on firmware_release table
ALTER TABLE firmware_release DROP CONSTRAINT firmware_release_firmware_component_hash_key;
ALTER TABLE firmware_release ADD CONSTRAINT firmware_release_part_type_firmware_component_hash_key UNIQUE (part_type, firmware_component, hash);
--  Inverters part_type split into Left/Right, leave `Inverters` part type alone for historical data/existing builds
INSERT INTO vehicle_part_types VALUES ('Inverter - Left');
INSERT INTO vehicle_part_types VALUES ('Inverter - Right');
-- insert new data in firmware_components and firmware_release tables
-- left
INSERT INTO firmware_components (part_type, firmware_component) VALUES ('Inverter - Left', 'Inverter Firmware');
INSERT INTO firmware_components (part_type, firmware_component) VALUES ('Inverter - Left', 'Inverter Profile - Left');
INSERT INTO firmware_release (part_type, firmware_component, description, hash) VALUES ('Inverter - Left', 'Inverter Firmware', 'Created from Inverter part type left/right split', (select hash from firmware_release where firmware_component = 'Inverter Firmware' order by firmware_release_id desc limit 1));
INSERT INTO firmware_release (part_type, firmware_component, description, hash) VALUES ('Inverter - Left', 'Inverter Profile - Left', 'Created from Inverter part type left/right split', (select hash from firmware_release where firmware_component = 'Inverter Profile - Left' order by firmware_release_id desc limit 1));
-- right
INSERT INTO firmware_components (part_type, firmware_component) VALUES ('Inverter - Right', 'Inverter Firmware');
INSERT INTO firmware_components (part_type, firmware_component) VALUES ('Inverter - Right', 'Inverter Profile - Right');
INSERT INTO firmware_release (part_type, firmware_component, description, hash) VALUES ('Inverter - Right', 'Inverter Firmware', 'Created from Inverter part type left/right split', (select hash from firmware_release where firmware_component = 'Inverter Firmware' order by firmware_release_id desc limit 1));
INSERT INTO firmware_release (part_type, firmware_component, description, hash) VALUES ('Inverter - Right', 'Inverter Profile - Right', 'Created from Inverter part type left/right split', (select hash from firmware_release where firmware_component = 'Inverter Profile - Left' order by firmware_release_id desc limit 1));

-- create entries in vehicle_model_parts for existing parts
-- FUV
-- FUV: Original Manufactured
-- no changes needed
-- FUV: Discoboard
-- update existing parts that need it
UPDATE vehicle_model_parts SET model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Discoboard') WHERE part_number = '004280';
UPDATE vehicle_model_parts SET firmware_release_id = (select firmware_release_id from vehicle_model_parts where part_type='Comm' and part_number='004280') WHERE part_type = 'Display' AND part_number = '004280';
-- skip Comm and Display create in FUV: Discoboard, already handled by UPDATEs above
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: Discoboard'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- FUV: KERS Sensor
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'Inverter - Left', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'Inverter - Right', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='FUV: KERS Sensor'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Camera Car
-- Camera Car: Original Manufactured
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Original Manufactured'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Camera Car: Discoboard
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: Discoboard'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Camera Car: KERS Sensor
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'Inverter - Left', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'Inverter - Right', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Camera Car: KERS Sensor'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Deliverator
-- Deliverator: Original Manufactured
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Original Manufactured'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Deliverator: Discoboard
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: Discoboard'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Deliverator: KERS Sensor
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'Inverter - Left', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'Inverter - Right', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Deliverator: KERS Sensor'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Rapid Responder
-- Rapid Responder: Original Manufactured
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Original Manufactured'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Rapid Responder: Discoboard
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: Discoboard'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Rapid Responder: KERS Sensor
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'Inverter - Left', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'Inverter - Right', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Rapid Responder: KERS Sensor'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Responderator
-- Responderator: Original Manufactured
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Original Manufactured'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Responderator: Discoboard
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: Discoboard'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Responderator: KERS Sensor
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'Inverter - Left', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'Inverter - Right', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Responderator: KERS Sensor'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Roadster
-- Roadster: Original Manufactured
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Original Manufactured'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Roadster: Discoboard
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'Inverters', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: Discoboard'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
-- Roadster: KERS Sensor
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'BMS', '001052', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'BMS'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'Charger', '004036', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Charger'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'Comm', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Comm'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'Display', '004280', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Display'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'EPSU', '001960', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'EPSU'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'H Bridge', '003223', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'H Bridge'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'Inverter - Left', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'Inverter - Right', '004085', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'Inverters'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'IO Front', '003225', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Front'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'IO Rear', '003224', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'IO Rear'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'LV', '004313', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'LV'));
INSERT INTO vehicle_model_parts (model_release_id, part_type, part_number, firmware_release_id) VALUES ((select model_release_id from vehicle_model_release where description='Roadster: KERS Sensor'), 'VCU', '003222', (select firmware_release_id from vehicle_model_parts where model_release_id = (select model_release_id from vehicle_model_release where description='FUV: Original Manufactured') AND part_type = 'VCU'));
