{
 "title": "replacetext_vin",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "VIN", "label": "VIN", "query": "show tag values with key=vin" },
   { "name": "telemetry1", "label": "telemetry 1", "query": "show field keys from telemetry" },
   { "name": "telemetry2", "label": "telemetry 2", "query": "show field keys from telemetry" },
   { "name": "telemetry3", "label": "telemetry 3", "query": "show field keys from telemetry" },
   { "name": "telemetry4", "label": "telemetry 4", "query": "show field keys from telemetry" },
   { "name": "temperature1", "label": "temperature 1", "query": "show field keys from telemetry" },
   { "name": "temperature2", "label": "temperature 2", "query": "show field keys from telemetry" },
   { "name": "temperature3", "label": "temperature 3", "query": "show field keys from telemetry" },
   { "name": "temperature4", "label": "temperature 4", "query": "show field keys from telemetry" },
   { "name": "voltage1", "label": "voltage 1", "query": "show field keys from telemetry" },
   { "name": "voltage2", "label": "voltage 2", "query": "show field keys from telemetry" },
   { "name": "voltage3", "label": "voltage 3", "query": "show field keys from telemetry" },
   { "name": "voltage4", "label": "voltage 4", "query": "show field keys from telemetry" },
   { "name": "current1", "label": "current 1", "query": "show field keys from telemetry" },
   { "name": "current2", "label": "current 2", "query": "show field keys from telemetry" },
   { "name": "current3", "label": "current 3", "query": "show field keys from telemetry" },
   { "name": "current4", "label": "current 4", "query": "show field keys from telemetry" }
  ]
 },
 "panels": [
  {
   "title": "Dynamic Panel: telemetry 1, telemetry 2, telemetry 3,  telemetry 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$telemetry1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry1) as $telemetry1 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$telemetry2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry2) as $telemetry2 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$telemetry3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry3) as $telemetry3 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$telemetry4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry4) as $telemetry4 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dynamic Panel: temperature 1, temperature 2, temperature 3, temperature 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$temperature1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($temperature1) as $temperature1 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$temperature2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($temperature2) as $temperature2 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$temperature3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($temperature3) as $temperature3 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$temperature4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($temperature4) as $temperature4 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dynamic Panel:  ( telemetry 1 - telemetry 2 )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$telemetry1 minus $telemetry2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry1) - mean($telemetry2) as [[telemetry1]]__minus__[[telemetry2]] FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dynamic Panel: voltage 1, voltage 2, voltage 3, voltage 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$voltage1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($voltage1) as $voltage1 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$voltage2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($voltage2) as $voltage2 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$voltage3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($voltage3) as $voltage3 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$voltage4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($voltage4) as $voltage4 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dynamic Panel: telemetry 1, telemetry 2, ( telemetry 1 - telemetry 2 )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$telemetry1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry1) as $telemetry1 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$telemetry2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry2) as $telemetry2 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$telemetry1 minus $telemetry2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($telemetry1) - mean($telemetry2) as  [[telemetry1]]__minus__[[telemetry2]]  FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dynamic Panel: current variable 1, current variable 2, current variable 3, current variable 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$current1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($current1) as $current1 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$current2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($current2) as $current2 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$current3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($current3) as $current3 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$current4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean($current4) as $current4 FROM \"telemetry\" WHERE $timeFilter  AND \"vin\"='$VIN' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}